//! Phase 4: the agent risk layer, end to end.
//!
//! Deploys the oracle, the agent registry, and the perp engine; wires the registry's executor
//! to the engine and the engine's registry to the registry; registers an agent; then drives a
//! real STARK-curve-signed ReduceSize proposal through `adjust_position`.
//!
//! The property under test is the trust model: the agent supplies only a signature, and the
//! *contracts* verify identity, signature, policy and nonce, then enforce the effect. A
//! compromised or lying agent is caught by the registry (bad signature, stale nonce, policy
//! breach) or by the engine (a reveal that does not match the commitment).
//!
//! Fixture position 'pp1' (a long): size 1000, entry 1500, margin 50000, leverage 2.
//! Proposal: ReduceSize by 2000 bps (20%) → new size 800. Signature from
//! scripts/gen_adjust_vector.mjs.

use starknet::syscalls::deploy_syscall;
use starknet::testing::set_contract_address;
use starknet::{ContractAddress, SyscallResultTrait};

use crate::agent_registry::{AgentRegistry, IAgentRegistryDispatcher, IAgentRegistryDispatcherTrait};
use crate::commitments::{compute_position_commitment, compute_trader_commitment};
use crate::perp::{IPerpEngineDispatcher, IPerpEngineDispatcherTrait, PerpEngine};
use crate::types::{AgentPolicy, SIDE_BUY};
use super::mock_oracle::MockOracle;

// Generated by scripts/gen_adjust_vector.mjs — do not edit by hand.
const ADJ_PUBLIC_KEY: felt252 = 0x20c29f1c98f3320d56f01c13372c923123c35828bce54f2153aa1cfe61c44f2;
const ADJ_POSITION_ID: felt252 = 0x707031; // 'pp1'
const ADJ_KIND: u8 = 1; // KIND_REDUCE_SIZE
const ADJ_VALUE: u128 = 2000; // 20%
const ADJ_NONCE: u64 = 0;
const ADJ_SIG_R: felt252 = 0x5517d5e98fad4ad9df40ffa9d5cb85ccf78c2d6c387bff7a23b6db9fba6e95;
const ADJ_SIG_S: felt252 = 0x12ca69b2de9bd4c6c14970f4a90f5a34b48fe807a6b8045e909c78b357c8871;

const SCALE: u128 = 1000000000000000000;
const ENTRY: u128 = 1500 * SCALE;
const POS_SIZE: u128 = 1000;
const NEW_SIZE: u128 = 800; // after 20% reduction
const POS_MARGIN: u128 = 50000;
const LEV: u8 = 2;
const POS_SALT: felt252 = 'pp_salt';
const NEW_SALT: felt252 = 'pp_new';

fn agent() -> ContractAddress {
    0xA9E17.try_into().unwrap()
}
fn base() -> ContractAddress {
    0xB45E.try_into().unwrap()
}
fn quote() -> ContractAddress {
    0x9074E.try_into().unwrap()
}

#[derive(Copy, Drop)]
struct World {
    registry: IAgentRegistryDispatcher,
    perp: IPerpEngineDispatcher,
}

fn policy(max_size_reduction_bps: u16) -> AgentPolicy {
    AgentPolicy {
        max_margin_increase_bps: 5000, max_size_reduction_bps, max_leverage: 5, may_close: true,
    }
}

/// Deploys and cross-wires all three contracts, registers the agent under `size_cap`, and opens
/// the fixture position. Leaves the caller context neutral.
fn setup(size_cap: u16) -> World {
    let (oracle_addr, _) = deploy_syscall(
        MockOracle::TEST_CLASS_HASH.try_into().unwrap(), 0, array![ENTRY.into()].span(), false,
    )
        .unwrap_syscall();
    let (registry_addr, _) = deploy_syscall(
        AgentRegistry::TEST_CLASS_HASH.try_into().unwrap(), 0, array![].span(), false,
    )
        .unwrap_syscall();
    let (perp_addr, _) = deploy_syscall(
        PerpEngine::TEST_CLASS_HASH.try_into().unwrap(), 0, array![oracle_addr.into()].span(),
        false,
    )
        .unwrap_syscall();

    let registry = IAgentRegistryDispatcher { contract_address: registry_addr };
    let perp = IPerpEngineDispatcher { contract_address: perp_addr };

    // Bind the two together: only the engine may consume proposals; the engine knows where to.
    registry.initialize_executor(perp_addr);
    perp.initialize_agent_registry(registry_addr);

    // Register the agent (caller must be the agent).
    set_contract_address(agent());
    registry.register_agent(ADJ_PUBLIC_KEY, policy(size_cap));
    set_contract_address(0.try_into().unwrap());

    // Open the fixture position.
    perp
        .open_position(
            ADJ_POSITION_ID,
            compute_trader_commitment('pos_owner'),
            compute_position_commitment(SIDE_BUY, POS_SIZE, ENTRY, POS_MARGIN, LEV, POS_SALT),
            base(),
            quote(),
        );

    World { registry, perp }
}

/// Submits the signed ReduceSize proposal against the current committed values.
fn adjust(w: World, size: u128, salt: felt252, nonce: u64) {
    w
        .perp
        .adjust_position(
            ADJ_POSITION_ID,
            SIDE_BUY,
            size,
            ENTRY,
            POS_MARGIN,
            LEV,
            salt,
            ADJ_KIND,
            ADJ_VALUE,
            agent(),
            nonce,
            ADJ_SIG_R,
            ADJ_SIG_S,
            NEW_SALT,
        );
}

// ---------------------------------------------------------------------------
// The happy path.
// ---------------------------------------------------------------------------

/// A valid signed proposal from a registered, in-policy agent applies, re-commits the reduced
/// position, and burns the nonce.
#[test]
fn a_valid_agent_proposal_reduces_the_position() {
    let w = setup(3000); // 2000 bps proposal is within a 3000 cap

    assert(w.registry.agent_nonce(agent()) == 0, 'nonce starts at 0');

    adjust(w, POS_SIZE, POS_SALT, 0);

    // The position is now committed to the reduced size under the new salt.
    let p = w.perp.get_position(ADJ_POSITION_ID);
    assert(
        p.commitment == compute_position_commitment(SIDE_BUY, NEW_SIZE, ENTRY, POS_MARGIN, LEV, NEW_SALT),
        'reduced commitment',
    );
    assert(p.open, 'still open');
    // Nonce burned — the same proposal can never apply again.
    assert(w.registry.agent_nonce(agent()) == 1, 'nonce burned');
}

// ---------------------------------------------------------------------------
// The contract catches a lying or stale agent.
// ---------------------------------------------------------------------------

/// A reveal that does not match the position's commitment is rejected by the engine before the
/// proposal is even consulted (threat T3 at the adjust leg).
#[test]
#[should_panic(expected: ('COMMITMENT_MISMATCH', 'ENTRYPOINT_FAILED'))]
fn a_false_reveal_is_rejected_by_the_engine() {
    let w = setup(3000);
    // Claim size 500 instead of the committed 1000.
    adjust(w, 500, POS_SALT, 0);
}

/// A proposal beyond the agent's policy is refused even with a valid signature (threat T5):
/// the registry raises POLICY_VIOLATION, which propagates through the engine's cross-call.
#[test]
#[should_panic(expected: ('POLICY_VIOLATION', 'ENTRYPOINT_FAILED', 'ENTRYPOINT_FAILED'))]
fn a_proposal_beyond_policy_is_refused() {
    let w = setup(1000); // cap 1000 bps < the signed 2000 bps
    adjust(w, POS_SIZE, POS_SALT, 0);
}

/// A stale nonce is refused. Demonstrated as a replay: after one successful adjustment, the
/// same signature (nonce 0) presented against the new committed values is rejected because the
/// registry has already burned nonce 0.
#[test]
#[should_panic(expected: ('STALE_NONCE', 'ENTRYPOINT_FAILED', 'ENTRYPOINT_FAILED'))]
fn a_burned_nonce_cannot_be_replayed() {
    let w = setup(3000);
    adjust(w, POS_SIZE, POS_SALT, 0); // succeeds, nonce -> 1
    // Reveal the new committed values (size 800, new salt) and replay the nonce-0 signature.
    adjust(w, NEW_SIZE, NEW_SALT, 0);
}

/// A signature that does not cover the submitted value is rejected. `value` is fixed by the
/// signed vector; tampering with the nonce to a fresh-but-unsigned value breaks the digest.
/// Here we present nonce 0 but against a tampered position reveal that still matches the
/// commitment is impossible, so instead we show a wrong agent: a valid signature does not
/// verify under a different registered agent.
#[test]
#[should_panic(expected: ('SIG_INVALID', 'ENTRYPOINT_FAILED', 'ENTRYPOINT_FAILED'))]
fn a_signature_does_not_verify_for_a_different_agent() {
    let w = setup(3000);

    // Register a second agent with a different key, active and in policy.
    let impostor: ContractAddress = 0xBAD.try_into().unwrap();
    set_contract_address(impostor);
    w
        .registry
        .register_agent(
            0x1ef15c18599971b7beced415a40f0c7deacfd9b0d1819e03d723d8bc943cfca, policy(3000),
        );
    set_contract_address(0.try_into().unwrap());

    // Submit agent A's signature but name the impostor as the agent.
    w
        .perp
        .adjust_position(
            ADJ_POSITION_ID, SIDE_BUY, POS_SIZE, ENTRY, POS_MARGIN, LEV, POS_SALT, ADJ_KIND,
            ADJ_VALUE, impostor, 0, ADJ_SIG_R, ADJ_SIG_S, NEW_SALT,
        );
}

/// The engine will not consume proposals until it is bound to a registry.
#[test]
#[should_panic(expected: ('REGISTRY_NOT_SET', 'ENTRYPOINT_FAILED'))]
fn an_unbound_engine_refuses_adjustments() {
    let (oracle_addr, _) = deploy_syscall(
        MockOracle::TEST_CLASS_HASH.try_into().unwrap(), 0, array![ENTRY.into()].span(), false,
    )
        .unwrap_syscall();
    let (perp_addr, _) = deploy_syscall(
        PerpEngine::TEST_CLASS_HASH.try_into().unwrap(), 0, array![oracle_addr.into()].span(),
        false,
    )
        .unwrap_syscall();
    let perp = IPerpEngineDispatcher { contract_address: perp_addr };
    perp
        .open_position(
            ADJ_POSITION_ID,
            compute_trader_commitment('pos_owner'),
            compute_position_commitment(SIDE_BUY, POS_SIZE, ENTRY, POS_MARGIN, LEV, POS_SALT),
            base(),
            quote(),
        );
    perp
        .adjust_position(
            ADJ_POSITION_ID, SIDE_BUY, POS_SIZE, ENTRY, POS_MARGIN, LEV, POS_SALT, ADJ_KIND,
            ADJ_VALUE, agent(), 0, ADJ_SIG_R, ADJ_SIG_S, NEW_SALT,
        );
}

/// Only the bound engine may consume proposals; a direct call to the registry is refused.
#[test]
#[should_panic(expected: ('NOT_EXECUTOR', 'ENTRYPOINT_FAILED'))]
fn a_direct_consume_bypassing_the_engine_is_refused() {
    let w = setup(3000);
    // Call the registry directly, not through the engine.
    w
        .registry
        .consume_proposal(agent(), ADJ_POSITION_ID, ADJ_KIND, ADJ_VALUE, 0, ADJ_SIG_R, ADJ_SIG_S);
}
