//! The accepting path for agent proposal verification, plus a cross-language check that
//! JavaScript and Cairo derive identical commitments.
//!
//! Fixtures come from `scripts/gen_signature_vector.mjs`, which signs with starknet.js and
//! refuses to emit a vector that fails local verification. Because the digest is computed
//! independently on both sides, a drift between the frontend's commitment scheme and the
//! contract's shows up here as a failing test rather than as a mainnet mismatch.

use starknet::ContractAddress;
use starknet::testing::set_caller_address;
use crate::agent_registry::AgentRegistry;
use crate::agent_registry::AgentRegistry::AgentRegistryImpl;
use crate::commitments::{
    compute_order_commitment, compute_proposal_digest, compute_trader_commitment,
};
use crate::types::{AgentPolicy, KIND_INCREASE_MARGIN, SIDE_BUY};

// Generated by scripts/gen_signature_vector.mjs — do not edit by hand.
const TEST_PUBLIC_KEY: felt252 = 0x20c29f1c98f3320d56f01c13372c923123c35828bce54f2153aa1cfe61c44f2;
const TEST_POSITION_ID: felt252 = 0x706f7331; // 'pos1'
const TEST_KIND: u8 = 0; // KIND_INCREASE_MARGIN
const TEST_VALUE: u128 = 2500; // 2500 bps
const TEST_NONCE: u64 = 0;
const TEST_SIG_R: felt252 = 0x5021fbfa873577f0561e992bf1f706d8779fb5f2163cfe59b289ca50931862d;
const TEST_SIG_S: felt252 = 0x3143e7b685b49892d3e8f832ab91f8c996225b37ba0ce54cf0baf7ce54d0b50;

const EXPECTED_DIGEST: felt252 = 0x6ce40525613069d02bbf0ff35a52c0a683514200b49454fe54bf723fa580e7e;
const EXPECTED_ORDER_COMMITMENT: felt252 =
    0x2fa3ca3b64d3af7ae08b7cf8966f96b2539dd9cc48e0e5541803d25368c2619;
const EXPECTED_TRADER_COMMITMENT: felt252 =
    0x25ea76ff0d343a2c94a4ec9100c60ddf421764bf873637edeffac41f4b61e5f;

fn state() -> AgentRegistry::ContractState {
    AgentRegistry::contract_state_for_testing()
}

fn agent() -> ContractAddress {
    0xA9E17.try_into().unwrap()
}

fn register(ref s: AgentRegistry::ContractState) {
    set_caller_address(agent());
    AgentRegistryImpl::register_agent(
        ref s,
        TEST_PUBLIC_KEY,
        AgentPolicy {
            max_margin_increase_bps: 5000,
            max_size_reduction_bps: 3000,
            max_leverage: 5,
            may_close: true,
        },
    );
}

// ---------------------------------------------------------------------------
// Cross-language agreement.
// ---------------------------------------------------------------------------

/// Cairo's Poseidon digest must equal the one starknet.js produced for the same inputs.
/// This is the check that keeps the off-chain agent signing exactly what the contract verifies.
#[test]
fn cairo_and_javascript_derive_the_same_proposal_digest() {
    let digest = compute_proposal_digest(TEST_POSITION_ID, TEST_KIND, TEST_VALUE, TEST_NONCE);
    assert(digest == EXPECTED_DIGEST, 'digest must match starknet.js');
}

/// Same agreement for the order commitment, which the frontend builds before placing.
#[test]
fn cairo_and_javascript_derive_the_same_order_commitment() {
    let commitment = compute_order_commitment(SIDE_BUY, 1500, 100, 'buy_salt');
    assert(commitment == EXPECTED_ORDER_COMMITMENT, 'order commit must match js');
}

#[test]
fn cairo_and_javascript_derive_the_same_trader_commitment() {
    let commitment = compute_trader_commitment('buyer_secret');
    assert(commitment == EXPECTED_TRADER_COMMITMENT, 'trader commit must match js');
}

// ---------------------------------------------------------------------------
// The accepting path.
// ---------------------------------------------------------------------------

/// A genuine signature from a registered agent, at the expected nonce and within policy,
/// verifies. This is the one path in the whole registry that returns true.
#[test]
fn a_valid_signed_proposal_verifies() {
    let mut s = state();
    register(ref s);

    let ok = AgentRegistryImpl::verify_proposal(
        @s,
        agent(),
        TEST_POSITION_ID,
        TEST_KIND,
        TEST_VALUE,
        TEST_NONCE,
        TEST_SIG_R,
        TEST_SIG_S,
    );
    assert(ok, 'valid proposal must verify');
}

/// The signature covers the whole proposal, so altering any signed field after the fact
/// invalidates it. Each case below reuses the genuine signature against tampered inputs.
#[test]
fn tampering_with_the_value_invalidates_the_signature() {
    let mut s = state();
    register(ref s);

    // Still inside policy (5000 bps), so this is rejected by the signature check rather
    // than by the bounds check — which is the property under test.
    let ok = AgentRegistryImpl::verify_proposal(
        @s, agent(), TEST_POSITION_ID, TEST_KIND, 4900, TEST_NONCE, TEST_SIG_R, TEST_SIG_S,
    );
    assert(!ok, 'tampered value must not verify');
}

#[test]
fn tampering_with_the_position_invalidates_the_signature() {
    let mut s = state();
    register(ref s);

    let ok = AgentRegistryImpl::verify_proposal(
        @s, agent(), 'pos2', TEST_KIND, TEST_VALUE, TEST_NONCE, TEST_SIG_R, TEST_SIG_S,
    );
    assert(!ok, 'tampered position rejected');
}

/// Redirecting a genuine margin proposal into a different action must fail. `KIND_REDUCE_SIZE`
/// is also within policy at 2500 bps, so again only the signature stands in the way.
#[test]
fn tampering_with_the_kind_invalidates_the_signature() {
    let mut s = state();
    register(ref s);

    let ok = AgentRegistryImpl::verify_proposal(
        @s, agent(), TEST_POSITION_ID, 1, TEST_VALUE, TEST_NONCE, TEST_SIG_R, TEST_SIG_S,
    );
    assert(!ok, 'tampered kind must not verify');
}

/// A valid signature from one agent must not verify under another agent's registration,
/// even when that agent is active and the proposal is otherwise well-formed.
#[test]
fn a_signature_does_not_transfer_between_agents() {
    let mut s = state();
    register(ref s);

    let impostor: ContractAddress = 0xBAD.try_into().unwrap();
    set_caller_address(impostor);
    AgentRegistryImpl::register_agent(
        ref s,
        // A different, well-formed key.
        0x1ef15c18599971b7beced415a40f0c7deacfd9b0d1819e03d723d8bc943cfca,
        AgentPolicy {
            max_margin_increase_bps: 5000,
            max_size_reduction_bps: 3000,
            max_leverage: 5,
            may_close: true,
        },
    );

    let ok = AgentRegistryImpl::verify_proposal(
        @s,
        impostor,
        TEST_POSITION_ID,
        TEST_KIND,
        TEST_VALUE,
        TEST_NONCE,
        TEST_SIG_R,
        TEST_SIG_S,
    );
    assert(!ok, 'signature must not transfer');
}

/// Threat T5, stated as a test: even a perfectly signed proposal from a live agent is refused
/// when it exceeds the registered policy. The signature proves authorship, never authority.
#[test]
fn a_valid_signature_cannot_exceed_policy() {
    let mut s = state();
    set_caller_address(agent());
    AgentRegistryImpl::register_agent(
        ref s,
        TEST_PUBLIC_KEY,
        // Policy now caps margin increases below the signed 2500 bps.
        AgentPolicy {
            max_margin_increase_bps: 1000,
            max_size_reduction_bps: 3000,
            max_leverage: 5,
            may_close: true,
        },
    );

    let ok = AgentRegistryImpl::verify_proposal(
        @s,
        agent(),
        TEST_POSITION_ID,
        KIND_INCREASE_MARGIN,
        TEST_VALUE,
        TEST_NONCE,
        TEST_SIG_R,
        TEST_SIG_S,
    );
    assert(!ok, 'policy outranks signature');
}

/// Revocation is immediate: a signature that verified a moment ago stops verifying.
#[test]
fn revocation_invalidates_a_previously_valid_proposal() {
    let mut s = state();
    register(ref s);

    let before = AgentRegistryImpl::verify_proposal(
        @s,
        agent(),
        TEST_POSITION_ID,
        TEST_KIND,
        TEST_VALUE,
        TEST_NONCE,
        TEST_SIG_R,
        TEST_SIG_S,
    );
    assert(before, 'valid before revocation');

    set_caller_address(agent());
    AgentRegistryImpl::revoke_agent(ref s);

    let after = AgentRegistryImpl::verify_proposal(
        @s,
        agent(),
        TEST_POSITION_ID,
        TEST_KIND,
        TEST_VALUE,
        TEST_NONCE,
        TEST_SIG_R,
        TEST_SIG_S,
    );
    assert(!after, 'invalid after revocation');
}
