use starknet::ContractAddress;
use starknet::testing::set_caller_address;
use crate::agent_registry::AgentRegistry;
use crate::agent_registry::AgentRegistry::AgentRegistryImpl;
use crate::types::{
    AgentPolicy, KIND_ADJUST_LEVERAGE, KIND_CLOSE_POSITION, KIND_INCREASE_MARGIN, KIND_REDUCE_SIZE,
};

fn state() -> AgentRegistry::ContractState {
    AgentRegistry::contract_state_for_testing()
}

fn agent() -> ContractAddress {
    0xA9E17.try_into().unwrap()
}

fn other() -> ContractAddress {
    0xB0B.try_into().unwrap()
}

const PUBKEY: felt252 = 0x1ef15c18599971b7beced415a40f0c7deacfd9b0d1819e03d723d8bc943cfca;

fn policy() -> AgentPolicy {
    AgentPolicy {
        max_margin_increase_bps: 5000, max_size_reduction_bps: 3000, max_leverage: 5, may_close: true,
    }
}

fn register(ref s: AgentRegistry::ContractState) {
    set_caller_address(agent());
    AgentRegistryImpl::register_agent(ref s, PUBKEY, policy());
}

#[test]
fn registration_makes_an_agent_active() {
    let mut s = state();
    register(ref s);

    assert(AgentRegistryImpl::is_registered_agent(@s, agent()), 'active after register');
    assert(AgentRegistryImpl::agent_public_key(@s, agent()) == PUBKEY, 'key stored');
    assert(AgentRegistryImpl::agent_nonce(@s, agent()) == 0, 'nonce starts at zero');
}

#[test]
fn an_unregistered_address_is_not_an_agent() {
    let s = state();
    assert(!AgentRegistryImpl::is_registered_agent(@s, other()), 'not registered');
    assert(AgentRegistryImpl::agent_public_key(@s, other()) == 0, 'no key');
}

#[test]
fn revocation_deactivates_the_agent() {
    let mut s = state();
    register(ref s);

    set_caller_address(agent());
    AgentRegistryImpl::revoke_agent(ref s);

    assert(!AgentRegistryImpl::is_registered_agent(@s, agent()), 'inactive after revoke');
}

/// Revocation is per-caller, so one agent cannot revoke another.
#[test]
#[should_panic(expected: ('NOT_REGISTERED',))]
fn a_stranger_cannot_revoke_an_agent() {
    let mut s = state();
    register(ref s);

    set_caller_address(other());
    AgentRegistryImpl::revoke_agent(ref s);
}

#[test]
#[should_panic(expected: ('ALREADY_REGISTERED',))]
fn an_active_agent_cannot_re_register() {
    let mut s = state();
    register(ref s);

    set_caller_address(agent());
    AgentRegistryImpl::register_agent(ref s, PUBKEY, policy());
}

#[test]
fn a_revoked_agent_can_register_again() {
    let mut s = state();
    register(ref s);

    set_caller_address(agent());
    AgentRegistryImpl::revoke_agent(ref s);
    AgentRegistryImpl::register_agent(ref s, PUBKEY, policy());

    assert(AgentRegistryImpl::is_registered_agent(@s, agent()), 'active again');
}

#[test]
#[should_panic(expected: ('ZERO_PUBLIC_KEY',))]
fn a_zero_public_key_is_rejected() {
    let mut s = state();
    set_caller_address(agent());
    AgentRegistryImpl::register_agent(ref s, 0, policy());
}

#[test]
#[should_panic(expected: ('LEVERAGE_TOO_HIGH',))]
fn leverage_above_the_venue_maximum_is_rejected() {
    let mut s = state();
    set_caller_address(agent());
    AgentRegistryImpl::register_agent(
        ref s,
        PUBKEY,
        AgentPolicy {
            max_margin_increase_bps: 5000,
            max_size_reduction_bps: 3000,
            max_leverage: 11,
            may_close: true,
        },
    );
}

#[test]
#[should_panic(expected: ('BPS_OUT_OF_RANGE',))]
fn a_basis_point_bound_above_100_percent_is_rejected() {
    let mut s = state();
    set_caller_address(agent());
    AgentRegistryImpl::register_agent(
        ref s,
        PUBKEY,
        AgentPolicy {
            max_margin_increase_bps: 10001,
            max_size_reduction_bps: 3000,
            max_leverage: 5,
            may_close: true,
        },
    );
}

// ---------------------------------------------------------------------------
// Proposal verification.
//
// These assert the *rejection* paths, which are the ones that carry the security
// property: an unregistered, revoked, stale, or out-of-policy proposal must never
// verify, whatever signature accompanies it. The accepting path needs a genuine
// STARK-curve signature over the Poseidon digest; that vector is generated by
// `scripts/gen_signature_vector.mjs` and asserted in `test_agent_signature.cairo`.
// ---------------------------------------------------------------------------

#[test]
fn an_unregistered_agent_never_verifies() {
    let s = state();
    let ok = AgentRegistryImpl::verify_proposal(
        @s, other(), 'pos1', KIND_INCREASE_MARGIN, 100, 0, 0x1, 0x2,
    );
    assert(!ok, 'unregistered must not verify');
}

#[test]
fn a_revoked_agent_never_verifies() {
    let mut s = state();
    register(ref s);
    set_caller_address(agent());
    AgentRegistryImpl::revoke_agent(ref s);

    let ok = AgentRegistryImpl::verify_proposal(
        @s, agent(), 'pos1', KIND_INCREASE_MARGIN, 100, 0, 0x1, 0x2,
    );
    assert(!ok, 'revoked must not verify');
}

/// Threat T6. A proposal bound to the wrong nonce is refused before the signature is even
/// checked, so a once-valid proposal cannot be replayed after the counter moves.
#[test]
fn a_stale_nonce_never_verifies() {
    let mut s = state();
    register(ref s);

    let ok = AgentRegistryImpl::verify_proposal(
        @s, agent(), 'pos1', KIND_INCREASE_MARGIN, 100, 42, 0x1, 0x2,
    );
    assert(!ok, 'stale nonce must not verify');
}

#[test]
fn a_garbage_signature_never_verifies() {
    let mut s = state();
    register(ref s);

    let ok = AgentRegistryImpl::verify_proposal(
        @s, agent(), 'pos1', KIND_INCREASE_MARGIN, 100, 0, 0xdead, 0xbeef,
    );
    assert(!ok, 'bad signature must not verify');
}

/// Policy is an upper bound the contract enforces. A margin top-up beyond the registered
/// ceiling must fail regardless of who signed it — this is the check that makes a
/// compromised agent key survivable (threat T5).
#[test]
fn a_proposal_beyond_policy_never_verifies() {
    let mut s = state();
    register(ref s);

    // policy() caps margin increases at 5000 bps.
    let ok = AgentRegistryImpl::verify_proposal(
        @s, agent(), 'pos1', KIND_INCREASE_MARGIN, 9000, 0, 0x1, 0x2,
    );
    assert(!ok, 'over-policy must not verify');
}

#[test]
fn an_unknown_proposal_kind_never_verifies() {
    let mut s = state();
    register(ref s);

    let ok = AgentRegistryImpl::verify_proposal(@s, agent(), 'pos1', 99, 1, 0, 0x1, 0x2);
    assert(!ok, 'unknown kind must not verify');
}

/// A close proposal from an agent whose policy forbids closing must be refused, even with
/// an otherwise well-formed request.
#[test]
fn a_close_is_refused_when_policy_forbids_it() {
    let mut s = state();
    set_caller_address(agent());
    AgentRegistryImpl::register_agent(
        ref s,
        PUBKEY,
        AgentPolicy {
            max_margin_increase_bps: 5000,
            max_size_reduction_bps: 3000,
            max_leverage: 5,
            may_close: false,
        },
    );

    let ok = AgentRegistryImpl::verify_proposal(
        @s, agent(), 'pos1', KIND_CLOSE_POSITION, 0, 0, 0x1, 0x2,
    );
    assert(!ok, 'close must be refused');
}

#[test]
fn policy_bounds_are_readable() {
    let mut s = state();
    register(ref s);

    let p = AgentRegistryImpl::agent_policy(@s, agent());
    assert(p.max_margin_increase_bps == 5000, 'margin bound');
    assert(p.max_size_reduction_bps == 3000, 'size bound');
    assert(p.max_leverage == 5, 'leverage bound');
    assert(p.may_close, 'may close');
}

/// Leverage adjustments are bounded above by policy and must name a real leverage figure;
/// zero would otherwise read as "no leverage" and slip through.
#[test]
fn a_zero_leverage_adjustment_never_verifies() {
    let mut s = state();
    register(ref s);

    let ok = AgentRegistryImpl::verify_proposal(
        @s, agent(), 'pos1', KIND_ADJUST_LEVERAGE, 0, 0, 0x1, 0x2,
    );
    assert(!ok, 'zero leverage refused');
}

#[test]
fn a_size_reduction_beyond_policy_never_verifies() {
    let mut s = state();
    register(ref s);

    let ok = AgentRegistryImpl::verify_proposal(
        @s, agent(), 'pos1', KIND_REDUCE_SIZE, 3001, 0, 0x1, 0x2,
    );
    assert(!ok, 'over-policy size refused');
}
