/**
 * Generates a STARK-curve signature vector for the agent-proposal test.
 *
 * This does double duty. It produces the accepting-path fixture that
 * `contracts/src/tests/test_agent_signature.cairo` asserts against, and — because the
 * digest is computed here in JavaScript and re-derived independently in Cairo — it proves
 * the frontend and the contract agree on the Poseidon commitment scheme. If those two ever
 * drift, the Cairo test fails rather than the mismatch surfacing on mainnet.
 *
 * Usage:  node scripts/gen_signature_vector.mjs
 */

import { ec, hash, shortString } from "starknet"

// Must match contracts/src/commitments.cairo exactly.
const PROPOSAL_TAG = shortString.encodeShortString("MG_PROPOSAL:V1")
const ORDER_COMMITMENT_TAG = shortString.encodeShortString("MG_ORDER_COMMIT:V1")
const TRADER_COMMITMENT_TAG = shortString.encodeShortString("MG_TRADER_COMMIT:V1")

// A throwaway key used only to produce a deterministic test fixture. It holds nothing,
// signs nothing outside this repository's tests, and is deliberately committed so the
// vector is reproducible by anyone reviewing the submission.
const TEST_PRIVATE_KEY = "0x1234567890987654321"

/** poseidon_hash_span over an array of felts, matching Cairo's core::poseidon. */
const poseidon = (felts) => hash.computePoseidonHashOnElements(felts)

const computeProposalDigest = (positionId, kind, value, nonce) =>
  poseidon([PROPOSAL_TAG, positionId, kind, value, nonce])

const computeOrderCommitment = (side, price, size, salt) =>
  poseidon([ORDER_COMMITMENT_TAG, side, price, size, salt])

const computeTraderCommitment = (ownerSecret) =>
  poseidon([TRADER_COMMITMENT_TAG, ownerSecret])

const publicKey = ec.starkCurve.getStarkKey(TEST_PRIVATE_KEY)

// KIND_INCREASE_MARGIN = 0, a 2500 bps top-up on position 'pos1' at nonce 0.
const positionId = shortString.encodeShortString("pos1")
const kind = 0
const value = 2500
const nonce = 0

const digest = computeProposalDigest(positionId, kind, value, nonce)
const signature = ec.starkCurve.sign(digest, TEST_PRIVATE_KEY)

// Verification takes the *full* public point, while Cairo's check_ecdsa_signature takes the
// x-coordinate alone — which is what getStarkKey returns and what we emit below.
const verified = ec.starkCurve.verify(signature, digest, ec.starkCurve.getPublicKey(TEST_PRIVATE_KEY))

console.log(`// Generated by scripts/gen_signature_vector.mjs — do not edit by hand.`)
console.log(`// Verified in JS before emission: ${verified}`)
console.log(`pub const TEST_PUBLIC_KEY: felt252 = ${publicKey};`)
console.log(`pub const TEST_POSITION_ID: felt252 = ${positionId};`)
console.log(`pub const TEST_KIND: u8 = ${kind};`)
console.log(`pub const TEST_VALUE: u128 = ${value};`)
console.log(`pub const TEST_NONCE: u64 = ${nonce};`)
console.log(`pub const TEST_SIG_R: felt252 = 0x${signature.r.toString(16)};`)
console.log(`pub const TEST_SIG_S: felt252 = 0x${signature.s.toString(16)};`)
console.log(``)
console.log(`// Cross-language checks — Cairo must derive these same values.`)
console.log(`// digest(pos1, 0, 2500, 0)`)
console.log(`pub const EXPECTED_DIGEST: felt252 = ${digest};`)
console.log(`// order commitment(SIDE_BUY=0, 1500, 100, 'buy_salt')`)
console.log(
  `pub const EXPECTED_ORDER_COMMITMENT: felt252 = ${computeOrderCommitment(
    0,
    1500,
    100,
    shortString.encodeShortString("buy_salt"),
  )};`,
)
console.log(`// trader commitment('buyer_secret')`)
console.log(
  `pub const EXPECTED_TRADER_COMMITMENT: felt252 = ${computeTraderCommitment(
    shortString.encodeShortString("buyer_secret"),
  )};`,
)

if (!verified) {
  console.error("signature failed local verification — refusing to emit a bad fixture")
  process.exit(1)
}
