/**
 * Signature vector for the Phase 4 agent-adjustment test.
 *
 * Signs a ReduceSize proposal (kind=1) over position 'pp1' at nonce 0, with the same throwaway
 * test key used in gen_signature_vector.mjs. Refuses to emit a vector that fails local
 * verification, and emits the digest so Cairo can cross-check it.
 *
 * Usage:  node scripts/gen_adjust_vector.mjs
 */

import { ec, hash, shortString } from "starknet"

const PROPOSAL_TAG = shortString.encodeShortString("MG_PROPOSAL:V1")
const TEST_PRIVATE_KEY = "0x1234567890987654321"

const poseidon = (f) => hash.computePoseidonHashOnElements(f)
const digestOf = (positionId, kind, value, nonce) =>
  poseidon([PROPOSAL_TAG, positionId, kind, value, nonce])

const publicKey = ec.starkCurve.getStarkKey(TEST_PRIVATE_KEY)
const positionId = shortString.encodeShortString("pp1")
const kind = 1 // KIND_REDUCE_SIZE
const value = 2000 // 2000 bps = 20% size reduction
const nonce = 0

const digest = digestOf(positionId, kind, value, nonce)
const sig = ec.starkCurve.sign(digest, TEST_PRIVATE_KEY)
const ok = ec.starkCurve.verify(sig, digest, ec.starkCurve.getPublicKey(TEST_PRIVATE_KEY))

console.log(`// Generated by scripts/gen_adjust_vector.mjs — do not edit by hand.`)
console.log(`// Verified in JS: ${ok}`)
console.log(`const ADJ_PUBLIC_KEY: felt252 = ${publicKey};`)
console.log(`const ADJ_POSITION_ID: felt252 = ${positionId}; // 'pp1'`)
console.log(`const ADJ_KIND: u8 = ${kind}; // KIND_REDUCE_SIZE`)
console.log(`const ADJ_VALUE: u128 = ${value};`)
console.log(`const ADJ_NONCE: u64 = ${nonce};`)
console.log(`const ADJ_SIG_R: felt252 = 0x${sig.r.toString(16)};`)
console.log(`const ADJ_SIG_S: felt252 = 0x${sig.s.toString(16)};`)
console.log(`const ADJ_DIGEST: felt252 = ${digest};`)

if (!ok) {
  console.error("signature failed local verification — refusing to emit")
  process.exit(1)
}
